name: CUDA Runtime Container

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/build-runtime-cuda-container.yml'
      - 'VIO/scripts/docker/runtime_cuda_amd64.dockerfile'

  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/build-runtime-cuda-container.yml'
      - 'VIO/scripts/docker/runtime_cuda_amd64.dockerfile'

jobs:
  Build-Runtime-CUDA-Container:
    runs-on: ubuntu-latest
    steps:
    -
      name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_ACCOUNT }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: Tools/Jetson/Cross-compile
        file: VIO/scripts/docker/runtime_cuda_amd64.dockerfile
        push: true
        tags: |
          jasonxxxyyy/sky-explorer:runtime-cuda11.4-ros2-amd64-${{ steps.date.outputs.today }}
          jasonxxxyyy/sky-explorer:runtime-cuda11.4-ros2-amd64 
