name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/docker-image.yml'
      - 'Tools/Jetson/Cross-compile/docker/*'
      
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/docker-image.yml'
      - 'Tools/Jetson/Cross-compile/docker/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: jasonxxxyyy
        password: dckr_pat_tWL1uiD7A4T6gkJfcPB_nmslkks
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: Tools/Jetson/Cross-compile
        file: Tools/Jetson/Cross-compile/docker/jetpack4.6.2-cuda10.2-ubuntu1804.dockerfile
        push: true
        tags: | 
          jasonxxxyyy/jetson-cross-compile:jetpack4.6.2-cuda10.2-ubuntu1804-${{ steps.date.outputs.today }}
          jasonxxxyyy/jetson-cross-compile:jetpack4.6.2-cuda10.2-ubuntu1804-latest
